import type { ToolMeta } from "@/types/tool";

/**
 * THE tool registry — single source of truth driving routing, nav, search, SEO.
 * Phases 1–4 complete.
 */
export const TOOLS: ToolMeta[] = [
  // ─── JSON ─────────────────────────────────────────────────────────────
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, prettify, and validate JSON with error reporting.",
    category: "json",
    keywords: ["json", "format", "beautify", "prettify", "validate"],
    icon: "{ }",
    load: () => import("@/components/tools/Formatter"),
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    description: "Minify JSON to a single compact line.",
    category: "json",
    keywords: ["json", "minify", "compress", "compact"],
    icon: "{}",
    load: () => import("@/components/tools/JsonMinifier"),
  },
  {
    id: "json-to-xml",
    name: "JSON to XML",
    description: "Convert JSON data into XML.",
    category: "json",
    keywords: ["json", "xml", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML",
    description: "Convert JSON data into YAML.",
    category: "json",
    keywords: ["json", "yaml", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "json-to-csv",
    name: "JSON to CSV",
    description: "Convert a JSON array into CSV.",
    category: "json",
    keywords: ["json", "csv", "convert", "table"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "json-to-tsv",
    name: "JSON to TSV",
    description: "Convert a JSON array into TSV.",
    category: "json",
    keywords: ["json", "tsv", "convert", "table"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "json-to-text",
    name: "JSON to Text",
    description: "Extract plain text values from JSON.",
    category: "json",
    keywords: ["json", "text", "plain", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "json-to-html",
    name: "JSON to HTML Table",
    description: "Convert a JSON array into an HTML table.",
    category: "json",
    keywords: ["json", "html", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON documents and see semantic differences.",
    category: "json",
    keywords: ["json", "diff", "compare", "difference"],
    icon: "Δ",
    load: () => import("@/components/tools/DataDiff"),
  },
  {
    id: "json-path-tester",
    name: "JSON Path Tester",
    description: "Evaluate JSONPath expressions against a JSON document.",
    category: "json",
    keywords: ["json", "jsonpath", "query", "path", "tester"],
    icon: "🔍",
    load: () => import("@/components/tools/JsonPathTester"),
  },
  {
    id: "json-stringify",
    name: "JSON Stringify",
    description: "Escape JSON for embedding in code as a string literal.",
    category: "json",
    keywords: ["json", "stringify", "escape", "encode"],
    icon: '""',
    load: () => import("@/components/tools/JsonStringify"),
  },
  {
    id: "json-serialize",
    name: "JSON Serialize",
    description: "Serialize a JSON value to an escaped string.",
    category: "json",
    keywords: ["json", "serialize", "escape"],
    icon: '""',
    load: () => import("@/components/tools/JsonStringify"),
  },
  {
    id: "json-deserialize",
    name: "JSON Deserialize",
    description: "Unescape a JSON string literal back to formatted JSON.",
    category: "json",
    keywords: ["json", "deserialize", "unescape", "decode"],
    icon: '""',
    load: () => import("@/components/tools/JsonStringify"),
  },
  {
    id: "string-to-json",
    name: "String to JSON",
    description: "Convert a plain string into a valid JSON value.",
    category: "json",
    keywords: ["string", "json", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/JsonStringify"),
  },
  // ─── XML ──────────────────────────────────────────────────────────────
  {
    id: "xml-formatter",
    name: "XML Formatter",
    description: "Format, prettify, and validate XML.",
    category: "xml",
    keywords: ["xml", "format", "beautify", "validate"],
    icon: "</>",
    load: () => import("@/components/tools/Formatter"),
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    description: "Convert XML documents into JSON.",
    category: "xml",
    keywords: ["xml", "json", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "xml-to-yaml",
    name: "XML to YAML",
    description: "Convert XML documents into YAML.",
    category: "xml",
    keywords: ["xml", "yaml", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "xml-to-csv",
    name: "XML to CSV",
    description: "Convert XML into CSV.",
    category: "xml",
    keywords: ["xml", "csv", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "xml-to-tsv",
    name: "XML to TSV",
    description: "Convert XML into TSV.",
    category: "xml",
    keywords: ["xml", "tsv", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "xml-to-text",
    name: "XML to Text",
    description: "Extract plain text from XML.",
    category: "xml",
    keywords: ["xml", "text", "strip", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "xml-to-html",
    name: "XML to HTML",
    description: "Convert XML into an HTML representation.",
    category: "xml",
    keywords: ["xml", "html", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "xml-diff",
    name: "XML Diff",
    description: "Compare two XML documents and highlight differences.",
    category: "xml",
    keywords: ["xml", "diff", "compare", "difference"],
    icon: "Δ",
    load: () => import("@/components/tools/XmlTools"),
  },
  {
    id: "xml-xsl-transform",
    name: "XML XSL Transform",
    description: "Apply an XSL stylesheet to an XML document.",
    category: "xml",
    keywords: ["xml", "xsl", "xslt", "transform"],
    icon: "⚙",
    load: () => import("@/components/tools/XmlTools"),
  },
  {
    id: "xml-stringify",
    name: "XML Stringify",
    description: "Escape an XML document into a string literal.",
    category: "xml",
    keywords: ["xml", "stringify", "escape", "encode"],
    icon: '""',
    load: () => import("@/components/tools/XmlTools"),
  },
  {
    id: "xpath-tester",
    name: "XPath Tester",
    description: "Evaluate XPath expressions against an XML document.",
    category: "xml",
    keywords: ["xpath", "xml", "query", "tester"],
    icon: "🔍",
    load: () => import("@/components/tools/XPathTester"),
  },
  // ─── CSV ──────────────────────────────────────────────────────────────
  {
    id: "csv-viewer",
    name: "CSV Viewer",
    description: "Render CSV data as an interactive table.",
    category: "csv",
    keywords: ["csv", "viewer", "table", "preview"],
    icon: "⊞",
    load: () => import("@/components/tools/CsvViewer"),
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV into a JSON array of objects.",
    category: "csv",
    keywords: ["csv", "json", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "csv-to-xml",
    name: "CSV to XML",
    description: "Convert CSV into XML.",
    category: "csv",
    keywords: ["csv", "xml", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "csv-to-yaml",
    name: "CSV to YAML",
    description: "Convert CSV into YAML.",
    category: "csv",
    keywords: ["csv", "yaml", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/DataConverter"),
  },
  {
    id: "csv-to-tsv",
    name: "CSV to TSV",
    description: "Convert CSV (comma-separated) to TSV (tab-separated).",
    category: "csv",
    keywords: ["csv", "tsv", "convert", "delimiter"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "csv-to-html",
    name: "CSV to HTML Table",
    description: "Convert CSV into an HTML table.",
    category: "csv",
    keywords: ["csv", "html", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "csv-to-sql",
    name: "CSV to SQL",
    description: "Generate SQL INSERT statements from CSV data.",
    category: "csv",
    keywords: ["csv", "sql", "insert", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  {
    id: "csv-to-multiline",
    name: "CSV to Multiline",
    description: "Convert CSV into readable multiline data.",
    category: "csv",
    keywords: ["csv", "multiline", "text", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/CsvConverter"),
  },
  // ─── SQL ──────────────────────────────────────────────────────────────
  {
    id: "sql-to-json",
    name: "SQL to JSON",
    description: "Convert SQL INSERT statements into JSON.",
    category: "sql",
    keywords: ["sql", "json", "insert", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/SqlConverter"),
  },
  {
    id: "sql-to-csv",
    name: "SQL to CSV",
    description: "Convert SQL INSERT statements into CSV.",
    category: "sql",
    keywords: ["sql", "csv", "insert", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/SqlConverter"),
  },
  {
    id: "sql-to-xml",
    name: "SQL to XML",
    description: "Convert SQL INSERT statements into XML.",
    category: "sql",
    keywords: ["sql", "xml", "insert", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/SqlConverter"),
  },
  {
    id: "sql-to-yaml",
    name: "SQL to YAML",
    description: "Convert SQL INSERT statements into YAML.",
    category: "sql",
    keywords: ["sql", "yaml", "insert", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/SqlConverter"),
  },
  {
    id: "sql-to-html",
    name: "SQL to HTML Table",
    description: "Convert SQL INSERT statements into an HTML table.",
    category: "sql",
    keywords: ["sql", "html", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/SqlConverter"),
  },
  // ─── HTML ─────────────────────────────────────────────────────────────
  {
    id: "html-stripper",
    name: "HTML Stripper",
    description: "Remove all HTML tags and return plain text.",
    category: "html",
    keywords: ["html", "strip", "remove tags", "plain text"],
    icon: "◆",
    load: () => import("@/components/tools/HtmlStripper"),
  },
  {
    id: "html-table-generator",
    name: "HTML Table Generator",
    description: "Generate an HTML table from CSV or TSV data.",
    category: "html",
    keywords: ["html", "table", "generate", "csv"],
    icon: "⊞",
    load: () => import("@/components/tools/HtmlTableGenerator"),
  },
  {
    id: "html-to-csv",
    name: "HTML to CSV",
    description: "Extract an HTML table and convert it to CSV.",
    category: "html",
    keywords: ["html", "csv", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-tsv",
    name: "HTML to TSV",
    description: "Extract an HTML table and convert it to TSV.",
    category: "html",
    keywords: ["html", "tsv", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-json",
    name: "HTML to JSON",
    description: "Extract an HTML table and convert it to JSON.",
    category: "html",
    keywords: ["html", "json", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-xml",
    name: "HTML to XML",
    description: "Extract an HTML table and convert it to XML.",
    category: "html",
    keywords: ["html", "xml", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-yaml",
    name: "HTML to YAML",
    description: "Extract an HTML table and convert it to YAML.",
    category: "html",
    keywords: ["html", "yaml", "table", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-text",
    name: "HTML to Text",
    description: "Strip HTML tags and return clean plain text.",
    category: "html",
    keywords: ["html", "text", "strip", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlConverter"),
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML into Markdown.",
    category: "html",
    keywords: ["html", "markdown", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/HtmlToMarkdown"),
  },
  {
    id: "html-to-pug",
    name: "HTML to PUG",
    description: "Convert HTML into PUG template syntax.",
    category: "html",
    keywords: ["html", "pug", "jade", "template", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/PugConverter"),
  },
  {
    id: "html-to-jade",
    name: "HTML to JADE",
    description: "Convert HTML into JADE (PUG) template syntax.",
    category: "html",
    keywords: ["html", "jade", "pug", "template", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/PugConverter"),
  },
  {
    id: "html-to-bbcode",
    name: "HTML to BBCode",
    description: "Convert HTML into BBCode.",
    category: "html",
    keywords: ["html", "bbcode", "forum", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/BbcodeConverter"),
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown into HTML.",
    category: "html",
    keywords: ["markdown", "html", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/MarkdownToHtml"),
  },
  {
    id: "pug-to-html",
    name: "PUG to HTML",
    description: "Render PUG templates as HTML.",
    category: "html",
    keywords: ["pug", "html", "template", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/PugConverter"),
  },
  {
    id: "jade-to-html",
    name: "JADE to HTML",
    description: "Render JADE (PUG) templates as HTML.",
    category: "html",
    keywords: ["jade", "pug", "html", "template", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/PugConverter"),
  },
  {
    id: "bbcode-to-html",
    name: "BBCode to HTML",
    description: "Convert BBCode to HTML.",
    category: "html",
    keywords: ["bbcode", "html", "forum", "convert"],
    icon: "⇄",
    load: () => import("@/components/tools/BbcodeConverter"),
  },
  {
    id: "text-to-html-entities",
    name: "Text to HTML Entities",
    description: "Encode reserved characters as HTML entities.",
    category: "html",
    keywords: ["html", "entities", "encode", "escape"],
    icon: "&",
    load: () => import("@/components/tools/HtmlEntities"),
  },
  {
    id: "html-entities-to-text",
    name: "HTML Entities to Text",
    description: "Decode HTML entities back to text.",
    category: "html",
    keywords: ["html", "entities", "decode", "unescape"],
    icon: "&",
    load: () => import("@/components/tools/HtmlEntities"),
  },
  // ─── Color ────────────────────────────────────────────────────────────
  ...colorTools(),
  // ─── Unit ─────────────────────────────────────────────────────────────
  ...unitTools(),
  // ─── Base64 ───────────────────────────────────────────────────────────
  {
    id: "text-to-base64",
    name: "Text to Base64",
    description: "Encode text as Base64.",
    category: "base64",
    keywords: ["base64", "encode", "text"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64"),
  },
  {
    id: "base64-to-text",
    name: "Base64 to Text",
    description: "Decode Base64 back to text.",
    category: "base64",
    keywords: ["base64", "decode", "text"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64"),
  },
  {
    id: "image-to-base64",
    name: "Image to Base64",
    description: "Encode any image file as a Base64 string.",
    category: "base64",
    keywords: ["image", "base64", "encode", "file"],
    icon: "⬡",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "base64-to-image",
    name: "Base64 to Image",
    description: "Decode a Base64 string into a viewable image.",
    category: "base64",
    keywords: ["base64", "image", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "png-to-base64",
    name: "PNG to Base64",
    description: "Encode a PNG image as Base64.",
    category: "base64",
    keywords: ["png", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "jpg-to-base64",
    name: "JPG to Base64",
    description: "Encode a JPG image as Base64.",
    category: "base64",
    keywords: ["jpg", "jpeg", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "json-to-base64",
    name: "JSON to Base64",
    description: "Encode JSON text as Base64.",
    category: "base64",
    keywords: ["json", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "xml-to-base64",
    name: "XML to Base64",
    description: "Encode XML text as Base64.",
    category: "base64",
    keywords: ["xml", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "yaml-to-base64",
    name: "YAML to Base64",
    description: "Encode YAML text as Base64.",
    category: "base64",
    keywords: ["yaml", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "csv-to-base64",
    name: "CSV to Base64",
    description: "Encode CSV text as Base64.",
    category: "base64",
    keywords: ["csv", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "tsv-to-base64",
    name: "TSV to Base64",
    description: "Encode TSV text as Base64.",
    category: "base64",
    keywords: ["tsv", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "hex-to-base64",
    name: "Hex to Base64",
    description: "Encode hexadecimal data as Base64.",
    category: "base64",
    keywords: ["hex", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "octal-to-base64",
    name: "Octal to Base64",
    description: "Encode octal data as Base64.",
    category: "base64",
    keywords: ["octal", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "binary-to-base64",
    name: "Binary to Base64",
    description: "Encode binary data as Base64.",
    category: "base64",
    keywords: ["binary", "base64", "encode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-json",
    name: "Base64 to JSON",
    description: "Decode Base64 back to JSON.",
    category: "base64",
    keywords: ["base64", "json", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-xml",
    name: "Base64 to XML",
    description: "Decode Base64 back to XML.",
    category: "base64",
    keywords: ["base64", "xml", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-yaml",
    name: "Base64 to YAML",
    description: "Decode Base64 back to YAML.",
    category: "base64",
    keywords: ["base64", "yaml", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-csv",
    name: "Base64 to CSV",
    description: "Decode Base64 back to CSV.",
    category: "base64",
    keywords: ["base64", "csv", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-tsv",
    name: "Base64 to TSV",
    description: "Decode Base64 back to TSV.",
    category: "base64",
    keywords: ["base64", "tsv", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-hex",
    name: "Base64 to Hex",
    description: "Decode Base64 to hexadecimal.",
    category: "base64",
    keywords: ["base64", "hex", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  {
    id: "base64-to-binary",
    name: "Base64 to Binary",
    description: "Decode Base64 to binary representation.",
    category: "base64",
    keywords: ["base64", "binary", "decode"],
    icon: "⬡",
    load: () => import("@/components/tools/Base64File"),
  },
  // ─── Image ────────────────────────────────────────────────────────────
  {
    id: "jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPG images to PNG format.",
    category: "image",
    keywords: ["jpg", "jpeg", "png", "convert", "image"],
    icon: "🖼",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG images to JPG format.",
    category: "image",
    keywords: ["png", "jpg", "jpeg", "convert", "image"],
    icon: "🖼",
    load: () => import("@/components/tools/ImageConverter"),
  },
  {
    id: "bmp-to-png",
    name: "BMP to PNG",
    description: "Convert BMP images to PNG format.",
    category: "image",
    keywords: ["bmp", "png", "convert", "image"],
    icon: "🖼",
    load: () => import("@/components/tools/ImageConverter"),
  },
  // ─── String ───────────────────────────────────────────────────────────
  {
    id: "case-converter",
    name: "Case Converter",
    description:
      "Convert text between camelCase, snake_case, kebab-case, and more.",
    category: "string",
    keywords: ["case", "camel", "snake", "kebab", "upper", "lower"],
    icon: "Aa",
    load: () => import("@/components/tools/CaseConverter"),
  },
  {
    id: "word-counter",
    name: "Word Counter",
    description: "Count characters, words, lines, and sentences.",
    category: "string",
    keywords: ["word", "count", "characters", "lines"],
    icon: "#",
    load: () => import("@/components/tools/WordCounter"),
  },
  {
    id: "word-frequency-counter",
    name: "Word Frequency Counter",
    description: "Count how often each word appears.",
    category: "string",
    keywords: ["word", "frequency", "count"],
    icon: "#",
    load: () => import("@/components/tools/WordFrequency"),
  },
  {
    id: "reverse-string",
    name: "Reverse String",
    description: "Reverse the characters of your text.",
    category: "string",
    keywords: ["reverse", "string", "flip"],
    icon: "↺",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "upside-down-text",
    name: "Upside Down Text",
    description: "Flip text upside down using Unicode.",
    category: "string",
    keywords: ["upside down", "flip", "text"],
    icon: "↻",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    description: "Remove repeated lines from your text.",
    category: "string",
    keywords: ["remove", "duplicate", "lines", "dedupe"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-empty-lines",
    name: "Remove Empty Lines",
    description: "Strip out blank lines.",
    category: "string",
    keywords: ["remove", "empty", "blank", "lines"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-extra-spaces",
    name: "Remove Extra Spaces",
    description: "Collapse repeated spaces and trim lines.",
    category: "string",
    keywords: ["remove", "spaces", "whitespace", "trim"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-whitespace",
    name: "Remove Whitespace",
    description: "Strip all whitespace from text.",
    category: "string",
    keywords: ["remove", "whitespace", "spaces"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-line-breaks",
    name: "Remove Line Breaks",
    description: "Replace line breaks with spaces.",
    category: "string",
    keywords: ["remove", "line breaks", "newline"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-lines-containing",
    name: "Remove Lines Containing",
    description: "Remove all lines that contain a given substring.",
    category: "string",
    keywords: ["remove", "lines", "filter", "containing"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "remove-accents",
    name: "Remove Accents",
    description: "Strip diacritical marks from accented characters.",
    category: "string",
    keywords: ["remove", "accents", "diacritics", "normalize"],
    icon: "≣",
    load: () => import("@/components/tools/WordSorter"),
  },
  {
    id: "remove-punctuation",
    name: "Remove Punctuation",
    description: "Strip all punctuation from text.",
    category: "string",
    keywords: ["remove", "punctuation", "symbols"],
    icon: "≣",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "sort-text-lines",
    name: "Sort Text Lines",
    description: "Sort lines alphabetically.",
    category: "string",
    keywords: ["sort", "lines", "alphabetical"],
    icon: "↕",
    load: () => import("@/components/tools/TextTransform"),
  },
  {
    id: "word-sorter",
    name: "Word Sorter",
    description: "Sort words alphabetically.",
    category: "string",
    keywords: ["sort", "words", "alphabetical"],
    icon: "↕",
    load: () => import("@/components/tools/WordSorter"),
  },
  {
    id: "word-repeater",
    name: "Word Repeater",
    description: "Repeat each word in your text N times.",
    category: "string",
    keywords: ["repeat", "word", "duplicate"],
    icon: "↻",
    load: () => import("@/components/tools/TextRepeater"),
  },
  {
    id: "text-repeater",
    name: "Text Repeater",
    description: "Repeat a block of text N times.",
    category: "string",
    keywords: ["repeat", "text", "duplicate"],
    icon: "↻",
    load: () => import("@/components/tools/TextRepeater"),
  },
  {
    id: "random-word-generator",
    name: "Random Word Generator",
    description: "Generate a list of random English words.",
    category: "string",
    keywords: ["random", "word", "generate"],
    icon: "⚄",
    load: () => import("@/components/tools/TextRepeater"),
  },
  {
    id: "number-to-word",
    name: "Number to Word",
    description: "Convert numbers to English words.",
    category: "string",
    keywords: ["number", "word", "convert", "spell"],
    icon: "123",
    load: () => import("@/components/tools/NumberWords"),
  },
  {
    id: "word-to-number",
    name: "Word to Number",
    description: "Convert English number words to digits.",
    category: "string",
    keywords: ["word", "number", "convert", "parse"],
    icon: "abc",
    load: () => import("@/components/tools/NumberWords"),
  },
  {
    id: "string-builder",
    name: "String Builder",
    description:
      "Build and manipulate strings with repeat and join operations.",
    category: "string",
    keywords: ["string", "builder", "repeat", "join"],
    icon: "⊕",
    load: () => import("@/components/tools/TextRepeater"),
  },
  {
    id: "delimited-text-extractor",
    name: "Delimited Text Extractor",
    description: "Extract a specific column from delimited text.",
    category: "string",
    keywords: ["delimited", "extract", "column", "split"],
    icon: "⊙",
    load: () => import("@/components/tools/TextRepeater"),
  },
  {
    id: "ntlm-hash",
    name: "NTLM Hash Generator",
    description: "Generate NTLM (MD4) hashes from text.",
    category: "string",
    keywords: ["ntlm", "hash", "md4", "windows"],
    icon: "#",
    load: () => import("@/components/tools/HashGenerator"),
  },
  {
    id: "string-to-hex",
    name: "String to Hex",
    description: "Encode text as hexadecimal bytes.",
    category: "string",
    keywords: ["string", "hex", "encode"],
    icon: "0x",
    load: () => import("@/components/tools/Encoder"),
  },
  {
    id: "hex-to-string",
    name: "Hex to String",
    description: "Decode hexadecimal bytes back to text.",
    category: "string",
    keywords: ["hex", "string", "decode"],
    icon: "0x",
    load: () => import("@/components/tools/Encoder"),
  },
  {
    id: "string-to-binary",
    name: "String to Binary",
    description: "Encode text as binary.",
    category: "string",
    keywords: ["string", "binary", "encode"],
    icon: "01",
    load: () => import("@/components/tools/Encoder"),
  },
  {
    id: "binary-to-string",
    name: "Binary to String",
    description: "Decode binary back to text.",
    category: "string",
    keywords: ["binary", "string", "decode"],
    icon: "01",
    load: () => import("@/components/tools/Encoder"),
  },
  {
    id: "password-generator",
    name: "Password Generator",
    description: "Generate strong, random passwords.",
    category: "utility",
    keywords: ["password", "generate", "random", "secure"],
    icon: "✦",
    load: () => import("@/components/tools/PasswordGenerator"),
  },
  // ─── Utility ──────────────────────────────────────────────────────────
  {
    id: "text-diff",
    name: "Text Diff",
    description: "Compare two blocks of text line by line.",
    category: "utility",
    keywords: ["diff", "compare", "text", "difference"],
    icon: "Δ",
    load: () => import("@/components/tools/DataDiff"),
  },
  {
    id: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to dates and vice versa.",
    category: "utility",
    keywords: ["unix", "timestamp", "date", "time", "epoch"],
    icon: "⏱",
    load: () => import("@/components/tools/UnixTimestamp"),
  },
  {
    id: "crontab-formatter",
    name: "Crontab Formatter",
    description: "Parse and explain cron expressions with next run times.",
    category: "utility",
    keywords: ["cron", "crontab", "schedule", "format"],
    icon: "⏰",
    load: () => import("@/components/tools/CrontabFormatter"),
  },
  {
    id: "credit-card-validator",
    name: "Credit Card Validator",
    description: "Validate credit card numbers using the Luhn algorithm.",
    category: "utility",
    keywords: ["credit card", "validate", "luhn", "visa", "mastercard"],
    icon: "💳",
    load: () => import("@/components/tools/CreditCard"),
  },
  {
    id: "credit-card-generator",
    name: "Credit Card Fake Generator",
    description: "Generate fake credit card numbers for testing (Luhn-valid).",
    category: "utility",
    keywords: ["credit card", "generate", "fake", "test", "luhn"],
    icon: "💳",
    load: () => import("@/components/tools/CreditCard"),
  },
  {
    id: "js-obfuscator",
    name: "JavaScript Obfuscator",
    description:
      "Obfuscate JavaScript code by renaming variables and encoding strings.",
    category: "utility",
    keywords: ["javascript", "obfuscate", "minify", "js"],
    icon: "🔒",
    load: () => import("@/components/tools/JsObfuscator"),
  },
];

/** Build the 30 color converter entries from format pairs. */
function colorTools(): ToolMeta[] {
  const formats: { id: string; label: string }[] = [
    { id: "hex", label: "HEX" },
    { id: "rgb", label: "RGB" },
    { id: "hsl", label: "HSL" },
    { id: "hsv", label: "HSV" },
    { id: "cmyk", label: "CMYK" },
    { id: "colortone", label: "Colortone" },
  ];
  const pairs: [string, string][] = [];
  for (const from of formats) {
    for (const to of formats) {
      if (from.id !== to.id) pairs.push([from.id, to.id]);
    }
  }
  return pairs.map(([from, to]) => {
    const fromLabel = formats.find((f) => f.id === from)!.label;
    const toLabel = formats.find((f) => f.id === to)!.label;
    return {
      id: `${from}-to-${to}`,
      name: `${fromLabel} to ${toLabel}`,
      description: `Convert ${fromLabel} colors to ${toLabel}.`,
      category: "color" as const,
      keywords: ["color", from, to, "convert", fromLabel, toLabel],
      icon: "◉",
      load: () => import("@/components/tools/ColorConverter"),
    };
  });
}

/** Build all unit converter entries. */
function unitTools(): ToolMeta[] {
  const cats: { id: string; name: string; kw: string[] }[] = [
    {
      id: "length-converter",
      name: "Length Converter",
      kw: ["meter", "feet", "inch", "mile"],
    },
    {
      id: "weight-converter",
      name: "Weight Converter",
      kw: ["gram", "kg", "pound", "ounce"],
    },
    {
      id: "volume-converter",
      name: "Volume Converter",
      kw: ["liter", "gallon", "cup"],
    },
    {
      id: "area-converter",
      name: "Area Converter",
      kw: ["square", "acre", "hectare"],
    },
    {
      id: "time-converter",
      name: "Time Converter",
      kw: ["second", "minute", "hour", "day"],
    },
    {
      id: "temperature-converter",
      name: "Temperature Converter",
      kw: ["celsius", "fahrenheit", "kelvin"],
    },
    {
      id: "speed-converter",
      name: "Speed Converter",
      kw: ["mph", "kph", "knot"],
    },
    {
      id: "data-storage-converter",
      name: "Data Storage Converter",
      kw: ["byte", "kb", "mb", "gb"],
    },
    {
      id: "pressure-converter",
      name: "Pressure Converter",
      kw: ["pascal", "psi", "bar", "atm"],
    },
    {
      id: "energy-converter",
      name: "Energy Converter",
      kw: ["joule", "calorie", "watt", "btu"],
    },
    {
      id: "angle-converter",
      name: "Angle Converter",
      kw: ["degree", "radian", "gradian"],
    },
  ];
  return cats.map((c) => ({
    id: c.id,
    name: c.name,
    description: `${c.name.replace(" Converter", "")} unit conversion.`,
    category: "unit" as const,
    keywords: ["unit", "convert", ...c.kw],
    icon: "⚖",
    load: () => import("@/components/tools/UnitConverter"),
  }));
}
